### ISSUE TITLE
多階層 checklist 勾選連動 / Auto check sub list items on checking parent

### ISSUE THREAD

**Issue by bestpika** [hackmdio/codimd#225]
不曉得有多階層的 checklist 勾選 high level 的時候能不能自動把底下一起勾起來?
- [ ] a
- [x] b <- 假設我勾這個
  - [x] c <- 這個自動勾
  - [x] d <- 這個也自動勾
    - [x] e <- 這個也自動勾

---

Is it possible to check sub list items when checking the parent item?
- [ ] a
- [x] b <- if I check this
  - [x] c <- this will be checked
  - [x] d <- this will be checked
    - [x] e <- this will be checked

**Comment by jackycute** [comment]
那如果使用者並不想自動勾子選項呢？

**Comment by bestpika** [comment]
設置一個 confirm 讓使用者確認？

**Comment by jackycute** [comment]
基本上會 follow GitHub 的設計，你按按看上面的清單，是不會自動勾選的
多按幾個勾還可以接受吧？

**Comment by bestpika** [comment]
我只是站在使用的立場而已
如果開發人員認為沒必要我也沒辦法啊 XD

**Comment by jackycute** [comment]
我們可以使用 gitter 討論比較細節的部份，確定需要開 issue 的再來這裡
https://gitter.im/hackmdio/hackmd?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by jackycute** [comment]
不要這麼著急，都是可以討論的
使用者有很多，需要多聽一點意見，憑我自己的意見不能作準
如果有甚麼需求可以先在 gitter 討論，有需要再來開 issue

**Comment by ccoenen** [comment]
(just jumping in here for the vote wanted label) I'm rarely using nested lists. I am perfectly Ok with the list not auto-checking anything else.

**Comment by ccoenen** [comment]
This is a very old ticket, and the "vote wanted" label didn't help much. I'll close this for now. If anyone were to work on this, their contribution would be welcome.
